### PR TITLE
Fix CICS connections breaking other ZE sessions

### LINKED ISSUE #124: VSCE: Unable to list `SIT-parms` for a region with self-signed certs
**Describe the bug**

Having rejectUnauthorized in the CICS profile (or base profile) does not matter when you try to show the SIT Parameters for the region

**Expected and actual results**

Expected to get the results of the following CICS reosurce
- Endpoint: `CICSSystemParameter`
- Parmameters: `PARMSRCE(COMBINED) PARMTYPE(SIT)`

Resulted in the following error:
image

**Describe your environment**

ZE VSCE: v2.15.2
CICS VSCE: v2.3.5
SCS: Yes

**Additional context**

N/A

### LINKED ISSUE #159: VSCE: using the CICS extension with a different host breaks Zowe Explorer
**Describe the bug**

I have multiple hosts in play.
hosta is a z/OSMF host which is https and using a self-signed certificate
hostb hosts a CMCI connection - either https with self-signed certificate or http (no ssl)
I am specifying `"rejectUnauthorized": false` on both profiles.

Using the CICS extension breaks the Zowe Explorer extension.

**Recreation steps**

I connect to hosta with z/OSMF correctly and browse data sets.
I connect to hostb with the CICS extension correctly and browse CICS resources.
I attempt to refresh my hosta z/OSMF data sets and receive this error: `Retrieving response from MVS list API Error: Failed to send an HTTP request.`

I reload my VS Code and able to connect to z/OSMF on hosta correctly, again.

If I stick to just using hostb consistently, I am able to use both z/OSMF and CMCI.

**Describe your environment**

- Zowe CLI version installed (run command `zowe --version`): CLI Version: 8.8.2, Zowe Release Version: v3.0.0
- Zowe Explorer version installed: 3.0.3
- Installed plug-ins and their version numbers (run command `zowe plugins list --short`): no plugins
- Installed z/OS-related VSCode Extensions and their version numbers: CICS - 3.0.1
- Node.js and NPM versions installed (run `node --version`, `npm --version`): v22.9.0, 10.8.3

### PR DESCRIPTION
**Pull request by AndrewTwydell**
**What It Does**
- Changes method of pulling data from CMCI from Axios HTTP requests to the CICS SDK's getResource and getCache methods
  - Removes makeRequest method - refactored response handling
  - Refactored getPlexInfo method into smaller methods depending on what's provided in the profile
- Removes the global rejectUnauthorized overrides which broke the other ZE sessions
- Created toArray utility to replace all cases where we had to do a Array.isArray check

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [ ] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**
Resolves #159
Resolves #124

### CODE REVIEW

File: packages/vsce/src/trees/treeItems/CICSLibraryTreeItem.ts [hunk 1]
```diff
@@ -58,35 +58,28 @@ export class CICSLibraryTreeItem extends TreeItem {
...
-      https.globalAgent.options.rejectUnauthorized = undefined;
-      const datasetArray = Array.isArray(libraryResponse.response.records.cicslibrarydatasetname)
-        ? libraryResponse.response.records.cicslibrarydatasetname
-        : [libraryResponse.response.records.cicslibrarydatasetname];
-      this.label = `${this.library.name}${this.parentRegion.parentPlex ? ` (${this.library.eyu_cicsname})` : ""}${
-        this.activeFilter ? ` (${this.activeFilter}) ` : " "
-      }[${datasetArray.length}]`;
+      const datasetArray = toArray(libraryResponse.response.records.cicslibrarydatasetname);
+      this.label = `${this.library.name}${this.parentRegion.parentPlex ? ` (${this.library.eyu_cicsname})` : ""}${this.activeFilter ? ` (${this.activeFilter}) ` : " "
+        }[${datasetArray.length}]`;
```
Comment (davenice) [inline packages/vsce/src/trees/treeItems/CICSLibraryTreeItem.ts:70]: this is a bit tricky and the whitespace has changed with no real benefit to the reader.

what about something like this? i guess the linter still won't like it, but...

```suggestion
      const datasetArray = toArray(libraryResponse.response.records.cicslibrarydatasetname);
      this.label = `${this.library.name}
        ${this.parentRegion.parentPlex ? ` (${this.library.eyu_cicsname})` : ""}
        ${this.activeFilter ? ` (${this.activeFilter}) ` : " "}
        [${datasetArray.length}]`;
```

Comment (davenice) [reply packages/vsce/src/trees/treeItems/CICSLibraryTreeItem.ts:70]: There are similar examples elsewhere, we could choose a common approach (whatever it is).

**Review by davenice — COMMENTED** [review]
Couple of thoughts - look generally good though.

File: packages/vsce/src/trees/treeItems/CICSLibraryTreeItem.ts (hunk 1 above)
Comment (AndrewTwydell) [reply packages/vsce/src/trees/treeItems/CICSLibraryTreeItem.ts]: Had a go at resolving in [this commit](https://github.com/zowe/cics-for-zowe-client/pull/173/commits/37980ec8493398fbc434908bc1b893630905bc41) - what do you think?

Comment (davenice) [reply packages/vsce/src/trees/treeItems/CICSLibraryTreeItem.ts]: I think that is way easier to maintain - guarantee it would take several goes to get the syntax, brackets, and backticks lined up any time I changed the previously implementation.

**Review by zFernand0 — APPROVED** [review]
Overall, LGTM! 😋 

Thanks for fixing up all the typing issues. 🙏 
And also for creating the common toArray function 🥳 
Finally, thanks a lot for removing `axios`! 🙏 

I know the primary purpose was to avoid messing with the reject unauthorized configuration of the https package, but I'm really happy with the little refactoring that happened here 🙏

**Comment by zFernand0** [comment]
> `@zFernand0` I'd like your opinion on this as it resolves an issue you found relating to self-signed certs.

My apologies for taking so long, 😅 
But I really like what's going on in this PR 🙏 

> I intend to squash my messy commits before merging 👍🏼

Similar to Zowe Explorer, I think we don't have to worry about constantly force-pushing to your own branch and instead, we can choose to squash PRs when merging (as Dave suggested on another PR conversation/thread).

Great work on this! 🙏

**Comment by zFernand0** [comment]
> With the current lack of automated testing (WIP), I'm recruiting as many people as possible to manually test this (`@davenice, @enamkhan, @chinmdas`, amongst others) but the more the merrier!

I'd love to see other people's thoughts/comments about their review/testing as well 🙏

File: packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedProgramTree.ts [hunk 2]
```diff
@@ -49,9 +50,8 @@ export class CICSCombinedProgramTree extends TreeItem {
         cancellable: true,
       },
       async (_, token) => {
-        token.onCancellationRequested(() => {
-          console.log("Cancelling the load");
-        });
+        token.onCancellationRequested(() => { });
```
Comment (enamkhan) [inline packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedProgramTree.ts:53]: Maybe () => true is fractionally neater.

Comment (enamkhan) [reply packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedProgramTree.ts:53]: Otherwise LGTM!

File: .editorconfig [hunk 3]
```diff
@@ -3,7 +3,7 @@ root = true
 
 [*]
 indent_style = space
-indent_size = 4
+indent_size = 2
```
[the remark this answers is not in the document]
Comment (AndrewTwydell) [reply .editorconfig:6]: From our experience (sometimes painful when they auto format on save back to indent of 4!) files already adhere. However that does not mean we shouldn't configure prettier on a format command or something 👍 

The reason for this change was to avoid the auto formatting moving the whole file around which will work in the meantime before we get a format command in. 🙂

**Comment by AndrewTwydell** [comment]
> Similar to Zowe Explorer, I think we don't have to worry about constantly force-pushing to your own branch and instead, we can choose to squash PRs when merging (as Dave suggested on another PR conversation/thread).
> 
I'm a fan of a tidy commit history so a habit I've found myself in! More for me than anything else 😂

File: packages/vsce/src/commands/enableCommands/enableTransactionCommand.ts [hunk 4]
```diff
@@ -99,7 +95,7 @@ export function getEnableTransactionCommand(tree: CICSTree, treeview: TreeView<a
   });
 }
 
-async function enableTransaction(session: imperative.AbstractSession, parms: { name: string; regionName: string; cicsPlex: string }): Promise<ICMCIApiResponse> {
+async function enableTransaction(session: imperative.AbstractSession, parms: { name: string; regionName: string; cicsPlex: string; }): Promise<ICMCIApiResponse> {
```
[the remark this answers is not in the document]
Comment (AndrewTwydell) [reply packages/vsce/src/commands/enableCommands/enableTransactionCommand.ts:98]: > Curious if we can type it as one
>
Good plan, I'll add that onto this PR while we're already touching those methods.

> Also, I know I have a draft PR (#14) about migrating a lot of these SDK-like functions to the `packages/sdk` but I'm afraid that such PR might be a bit ambitious and also out of date 😋
> 
Now I'm more familiar with the monorepo I'll look over what you've got and comment over there. Seems silly to waste effort you've already done! 😎

**Comment by davenice** [comment]
I've had a go with:
- two separate hosts in play for z/OSMF, one with proper cert and one self-signed - both secured
- cicsplexes on one of the hosts - one with security (incl self signed ssl) and one without security

I can access all of these systems at once without an issue.

i'm seeing a possible regression around what happens if you connect to a plex but specify a regionName - it seems to be displaying the "All Programs" and similar menus, and nesting everything as if it's a whole plex.

image

File: packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedProgramTree.ts (hunk 2 above)
Comment (AndrewTwydell) [reply packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedProgramTree.ts:53]: We can do this in a follow-up refactor if that's okay! 😄

File: .editorconfig (hunk 3 above)
[the remark this answers is not in the document]
Comment (davenice) [reply .editorconfig:6]: Yes - we're having quite a few issues with whole files changing, and having to ask people to undo some of the changes they didn't intend (also issues with the changelog causing a conflict with every PR!)

If preferred, we could set this to 2 in a separate PR and format EVERYTHING so that we get that out of the way in one bash.

**Comment by AndrewTwydell** [comment]
Good find @davenice! Will take a look now... Is that where you've specified a plex and region in the profile, not through any filtering

**Comment by davenice** [comment]
> Good find @davenice! Will take a look now... Is that where you've specified a plex and region in the profile, not through any filtering

yes that's right - I think the issue is in profileManagement where we're deciding whether we've specified a region or group, the code is thinking we specified a group.

File: packages/vsce/src/utils/profileManagement.ts [hunk 5]
```diff
@@ -52,273 +53,292 @@ export class ProfileManagement {
...
+      });
+    } catch (error) {
+      if (error instanceof imperative.ImperativeError) {
+        if (!error.mDetails.msg.toUpperCase().includes("NODATA")) {
+          throw error;
+        }
+      }
+    }
+
+    return checkIfSystemGroup?.response.resultsummary.recordcount !== "0";
```
Comment (davenice) [inline packages/vsce/src/utils/profileManagement.ts:90]: If we get an error (like NODATA), checkIfSystemGroup is still undefined, which means it isn't "0", which means we return true ... which is wrong.

I think the best thing to do is assign the recordcount to a variable and make sure it's defined. If it is, and it's non null - we got ourselves a result. Another option would be to parse it as an int and check it was greater than zero, but I suspect this will have its own issues.

```suggestion
    var recordCount = checkIfSystemGroup?.response.resultsummary.recordcount;
    return typeof recordCount !== "undefined" && recordCount !== "0";
```

File: .editorconfig (hunk 3 above)
[the remark this answers is not in the document]
Comment (zFernand0) [reply .editorconfig:6]: I like the idea of doing it on a separate PR 🙏 
Thank you both for considering this! 🙏

File: packages/vsce/src/utils/profileManagement.ts (hunk 5 above)
Comment (davenice) [reply packages/vsce/src/utils/profileManagement.ts:90]: After a discussion with Andrew we came up with a clearer option... I'll suggest that separately.

File: packages/vsce/src/utils/profileManagement.ts [hunk 6]
```diff
@@ -52,273 +53,292 @@ export class ProfileManagement {
...
+  }
```
Comment (davenice) [inline packages/vsce/src/utils/profileManagement.ts:91]: If we get an error (like NODATA), checkIfSystemGroup is still undefined, which means it isn't "0", which means we return true ... which is wrong.

Making the flow clearer and ensuring we set group to false if checkIfSystemGroup is undefined will give the right result.

```suggestion
  public static async regionIsGroup(session: Session, profile: imperative.IProfile): Promise<boolean> {
    let isGroup = false;

    try {
      const checkIfSystemGroup: ICMCIApiResponse = await getResource(session, {
        name: "CICSRegionGroup",
        cicsPlex: profile.cicsPlex,
        regionName: profile.regionName,
        criteria: `GROUP=${profile.regionName}`,
      });

      if (checkIfSystemGroup && checkIfSystemGroup.response.resultsummary.recordcount !== "0") {
        isGroup = true;
      }
    } catch (error) {
      if (error instanceof imperative.ImperativeError) {
        if (!error.mDetails.msg.toUpperCase().includes("NODATA")) {
          throw error;
        }
      }
    }

    return isGroup;
  }
```

**Comment by davenice** [comment]
OK - so I think we've resolved the issues we know about. I've tested with SMSS now (had forgotten that before).

Is there much else remaining to snag on this, @AndrewTwydell? I aspire to us getting this in this week ... if it's safe :-)

**Comment by AndrewTwydell** [comment]
Nothing more that's been mentioned or found, and lots of manual testing has now been done. Seems I've got some fun conflicts to resolve later and we can hopefully get it in this afternoon after a final nod from the reviewers 🙂 Be very good to finally have this problem sorted!!!

**Comment by zFernand0** [comment]
> We're pretty confident that this is an improvement now (within the bounds that there isn't much automated testing).
> 
> We'd like to get this in - are you happy?

**_100%_** 
Thank you all for giving this a try and special shoutout to Andrew for the refactoring (and removing `axios` 🙏  )
